### ISSUE TITLE
Add artificial intelligence to portfolio

### ISSUE THREAD

**Issue by ebron01** [devcurio-team/website#8]

**Comment by evg1n** [comment]
sadece artificial intelligence mi

yoksa ai/ml şeklinde mi koyalım

kısa bir desc eklerseniz süpo olur

@ebron01 @balamir53

**Comment by ebron01** [comment]
Businesses that do not harness the power of AI are at a disadvantage in today's competitive landscape. AI, Machine Learning and Deep Learning are powerful tools that can help businesses to automate tasks, improve efficiency, make better decisions, discover new insights and solve complex problems. By failing to adopt AI, businesses are limiting their potential and putting themselves at a disadvantage.

**Comment by ebron01** [comment]
Baslik olarak Artifical Intelligence yazalim.
